version: '3'

networks:
  pspbackEnd:

services:

  psp-back-end-db:
    image: mysql:5.5
    networks:
      - pspbackEnd
    ports:
      - 3311:3306
    environment:
      - MYSQL_ROOT_PASSWORD=psp
      - MYSQL_DATABASE=psp
      - MYSQL_USER=psp
      - MYSQL_PASSWORD=psp

  psp-back-end-service:
    image: nosbielc/psp-backend:091920192321
    networks:
      - pspbackEnd
    ports:
      - 3001:3000
    restart: always
    environment:
      - PSP_HOST_DB_ENV=psp-back-end-db
      - PSP_PORT_ENV=3306
      - PSP_DATABASE_ENV=psp
      - PSP_DIALECT_ENV=mysql
      - PSP_USER_NAME_ENV=psp
      - PSP_PASSWORD_ENV=psp
    depends_on:
      - psp-back-end-db
